version: 2

defaults: &defaults
  working_directory: ~/project/toy-robot-cli
  docker:
    - image: circleci/node:9

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "yarn.lock" }}
            - v2-dependencies-
      - run: yarn
      - save_cache:
          key: v2-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/project
          paths:
            - toy-robot-cli

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn test
      - run: yarn codecov

workflows:
  version: 2
  install-and-test:
    jobs:
      - install
      - test:
          requires:
            - install
